### ISSUE TITLE
能不能讲讲怎么绑定M cmd键

### ISSUE THREAD

**Issue by lijing-2008** [LintaoAmons/CoolStuffes#1]
["RunCurrentBuffer"] =  M-r
饕哥，我很想要这个功能，就是运行当前代码，我用的neovide，通过item打开的，有什么办法吗？请指导啊。。

**Comment by LintaoAmons** [comment]
- 你要确定你有没有 `RunCurrentBuffer` 这个 command（我这个命令是包装了下sniprun 的命令）
- neovide use <D-key> represents the cmd key in mac, 然后要注意这个

**Comment by LintaoAmons** [comment]
能帮忙关一下 issue 吗？如果你已经搞定了～
