### ISSUE TITLE
<D-e>这个D是什么键啊？

### ISSUE THREAD

**Issue by dnxxymcj** [LintaoAmons/CoolStuffes#2]
vim.keymap.set(
    "n",
    "<D-e>",
    "<cmd>Telescope frecency workspace=CWD<cr>",
    { desc = "FindRecentFiles" }
  )

**Comment by LintaoAmons** [comment]
https://github.com/LintaoAmons/CoolStuffes/blob/8baea4c86be1e0ec4c6226ce9c4dde094c25c6a8/lazyvim/.config/nvim/lua/config/keymaps.lua#L73
你是指这个吗？

**Comment by dnxxymcj** [comment]
> https://github.com/LintaoAmons/CoolStuffes/blob/8baea4c86be1e0ec4c6226ce9c4dde094c25c6a8/lazyvim/.config/nvim/lua/config/keymaps.lua#L73
> 
> 
> 你是指这个吗？

是，谢谢了
