### ISSUE TITLE
Neovim multicursor issue

### ISSUE THREAD

**Issue by edevil** [LintaoAmons/CoolStuffes#3]
Hello.

I am interested in your Neovim/Lazyvim [configuration](https://github.com/LintaoAmons/CoolStuffes/blob/main/lazyvim/.config/nvim/lua/plugins/multi-cursor.lua) for the `mg979/vim-visual-multi` plugin, however it doesn't seem to be working in my setup.

As a VsCode convert I was just trying to select various instances of the word under the cursor, which if I read the config correctly is mapped to `<M-b>` or `ALT-b`, am I right?

I just copied that config file and put it in the plugins/ dir of a fresh LazyVim installation. Is the plugin working correctly for you?

Thanks.

**Comment by LintaoAmons** [comment]
Yeah, mine is working~ 

![show](https://github.com/LintaoAmons/CoolStuffes/assets/95092244/1e1a5ffd-f2b7-45b6-847e-bbd34313fe6c)

You may mapping to another key to just test if it's just the keymapping's issue

**Comment by edevil** [comment]
Thanks for letting me know.
